### create/post
POST http://localhost:5341/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Test",
    "lastName": "Testerson",
    "email": "test@test.test",
    "favoriteColor": "test",
    "birthday": "te-st-test"
}

### read/get
GET http://localhost:5341/contacts/<id>

### read/get all
GET http://localhost:5341/contacts

### update/put
PUT http://localhost:5341/contacts/<id> HTTP/1.1
Content-Type: application/json

{
    "firstName": "Testmund",
    "email": "testing@test.test",
    "birthday": "73-27-7327"
}

### delete
DELETE http://localhost:5341/contacts/<id>
